apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     trace
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-systemd.conf: |
    [INPUT]
      Name            systemd
      Path            /journal
      Tag             systemd.*

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Refresh_Interval  10
        Streams_File stream_processor.conf
        routable Off

  stream_processor.conf: |
    [STREAM_TASK]
        Name   applog
        Exec CREATE STREAM payloads WITH(tag='applog') AS SELECT * FROM STREAM:tail.0 WHERE @record.contains(exc_info);
        Exec CREATE STREAM nopayloads WITH(tag='systemlog') AS SELECT * FROM STREAM:tail.0 WHERE NOT @record.contains(exc_info);

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Keep_Log            Off
        Merge_Log           On
  
  filter-systemd.conf: |
    [FILTER]
        Name modify
        Match systemd.*
        Rename _SYSTEMD_UNIT systemd_unit
        Rename _HOSTNAME hostname
    
    [FILTER]
        Name record_modifier
        Match systemd.*
        Remove_Key _CURSOR
        Remove_Key _REALTIME_TIMESTAMP
        Remove_Key _MONOTONIC_TIMESTAMP 
        Remove_Key _BOOT_ID
        Remove_Key _MACHINE_ID

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           systemd.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        
        Logstash_Format True
        Logstash_Prefix fluent-bit
        Retry_Limit     False

    [OUTPUT]
        Name            es
        Match           systemlog 
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        
        Logstash_Format True
        Logstash_Prefix fluent-bit
        Retry_Limit     False

    [OUTPUT]
        Name            es-1
        Match           applog
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        
        Logstash_Format True
        Logstash_Prefix fluent-bit-app-log
        Retry_Limit     False


  parsers.conf: |

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
