apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    k8s-app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    k8s-app: elasticsearch
    version: v7.3.1 
spec:  
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v7.3.1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v7.3.1
    spec:
      serviceAccountName: elasticsearch
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        name: elasticsearch
        imagePullPolicy: Always
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch
          mountPath: /data       
      volumes:
      - name: elasticsearch
        emptyDir: {}
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init
        securityContext:
          privileged: true
