apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: inter-node
  selector:
    k8s-app: elasticsearch
